apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook
  labels:
    app: certmaster
webhooks:
  - name: certmaster.default.svc.cluster.local
    clientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        name: certmaster
        namespace: default
        path: "/mutate"
        port: 8443
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        certmaster: enabled